CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(25) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
    -- REFERENCES users.id ON DELETE CASCADE,
  movie_id CHAR(10) NOT NULL,
  username VARCHAR(25) NOT NULL,
    -- REFERENCES users.username ON DELETE CASCADE,
  comment VARCHAR(1000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorites (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
    -- REFERENCES users.id ON DELETE CASCADE,
  movie_id CHAR(10) NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  favorite BOOLEAN NOT NULL DEFAULT FALSE
);